stages:
  - pre-merge-check

.pre_merge_template: &pre_merge_template
  image: maven:3.9-eclipse-temurin-24
  tags:
    - docker
  stage: pre-merge-check
  script:
    - mvn --batch-mode --update-snapshots verify
  only:
    - merge_requests
  rules:
    - if: '$CI_MERGE_REQUEST_ID'

pre_merge_check_backendswt:
  <<: *pre_merge_template
  variables:
    MAVEN_PROJECT_DIR: "BackendSWT"
  before_script:
    - cd $MAVEN_PROJECT_DIR
