stages:
  - build
  - docker

variables:
  MAVEN_CLI_OPTS: "-B -U"
  GIT_DEPTH: 0
  DOCKER_DRIVER: overlay2

default:
  image: maven:3.9.3-eclipse-temurin-22
  tags:
    - docker

before_script:
  - echo "Using JDK version 22 and Maven"
  - export PROJECT="BackendSWT"

build_jar:
  stage: build
  script:
    - cd $PROJECT
    - mvn $MAVEN_CLI_OPTS package
  artifacts:
    paths:
      - $PROJECT/target/*.jar

docker_build_push:
  stage: docker
  image: docker:24.0.5
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - export IMAGE_TAG="${CI_REGISTRY_IMAGE}/${PROJECT}:${CI_COMMIT_SHA}"
    - docker build -t "$IMAGE_TAG" $PROJECT
    - docker push "$IMAGE_TAG"
  only:
    - main
