package backend.stadt.enums;

public enum FilterCategory {
    YOUTH_CENTERS,
    HOLIDAY_OFFERS,
    PLAY_LEARN_AND_EXPERIENCE,
    SPORT_AND_EXERCISE,
    ENGAGEMENT_AND_VOLUNTEERING,
    CREATIVITY_AND_CULTURE,
    PARKS_AND_PLAYGROUNDS,
    FESTIVALS_AND_MARKETS,
    OTHER_OFFERS_LEISURE,
    DAYCARE,
    EMERGENCY_CARE,
    BABYSITTER,
    OTHER_OFFERS_CARE
}
