name: Publish Docker Images

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - backend-stadt
          - mqtt-connector
          - kidsapp-application

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Verify Java setup
        run: |
          java -version
          mvn -v

      - name: Build project ${{ matrix.project }}
        working-directory: ./${{ matrix.project }}
        run: mvn --batch-mode --update-snapshots package -DskipTests

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT || secrets.GITHUB_TOKEN}}

      - name: Build & push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.project }}
          file: ./${{ matrix.project }}/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.project }}:latest
